[package]
name = "environment-cleaner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
powershell_script = "0.2.1"
clap = "3.0.0-beta.2"
serde = "1.0"
serde_yaml = "0.8"